CREATE TABLE trip (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    DESTINATION VARCHAR(255) NOT NULL,
    STARTS_AT TIMESTAMP NOT NULL,
    ENDS_AT TIMESTAMP NOT NULL,
    IS_CONFIRMED BOOLEAN NOT NULL,
    OWNER_NAME VARCHAR(255) NOT NULL,
    OWNER_EMAIL VARCHAR(255) NOT NULL
);